# The ISP scenario for which to generate ISPyPSA inputs
# Options (descriptions lifted from the 2024 ISP):
#   "Progressive Change": Reflects slower economic growth and energy investment with
#       economic and international factors placing industrial demands at greater risk and slower
#       decarbonisation action beyond current commitments
#   "Step Change": Fulfils Australia’s emission reduction commitments in a growing economy
#   "Green Energy Exports": Sees very strong industrial decarbonisation and low-emission energy exports
scenario: Step Change
temporal_resolution: 30min
network:
  nodes:
    # The regional granularity of the nodes in the modelled network
    # Options:
    #   "sub_regions": ISP sub-regions are added as network nodes (12 nodes)
    #   "nem_regions": NEM regions are added as network nodes (5 nodes)
    #   "single_region": A single node, the Victorian sub-region, is added as a network node (1 node)
    #   TODO: Clarify `single_region`/`copper_plate` implementation
    regional_granularity: sub_regions
    # Whether Renewable Energy Zones (REZs) are modelled as distinct nodes
    # Options:
    #   "discrete_nodes": REZs are added as network nodes to model REZ transmission limits
    #   "attached_to_parent_node": REZ resources are attached to their parent node (sub-region or NEM region)
    rezs: discrete_nodes
traces:
  year_type: fy
  start_year: 2025
  end_year: 2025
  reference_year_cycle: [2018]
# External solver to use
# Options (refer to https://pypsa.readthedocs.io/en/latest/getting-started/installation.html):
#   Free, and by default, installed with ISPyPSA:
#     "highs"
#   Free, but must be installed by the user:
#     "cbc"
#     "glpk"
#     "scip"
#   Not free and must be installed by the user:
#     "cplex"
#     "gurobi"
#     "xpress"
#     "mosek"
#     "copt"
#     "mindopt"
#     "pips"
solver: highs
