# The ISP scenario for which to generate ISPyPSA inputs
# Options (descriptions lifted from the 2024 ISP):
#   "Progressive Change": Reflects slower economic growth and energy investment with
#       economic and international factors placing industrial demands at greater risk and slower
#       decarbonisation action beyond current commitments
#   "Step Change": Fulfils Australia’s emission reduction commitments in a growing economy
#   "Green Energy Exports": Sees very strong industrial decarbonisation and low-emission energy exports
scenario: Step Change
network:
  # The geographical granularity of the modelled network (i.e. the number of network nodes)
  # Options:
  #   "sub_regional": ISP Sub-regions are used to create network nodes (12 nodes)
  #   "regional": NEM regions are used to create network nodes (5 nodes)
  #   "single_region": Existing generation and new entrants for the Victorian sub-region are attached to a single node (1 node)
  #   TODO: Clarify `single_region`/`copper_plate` implementation
  granularity: sub_regional
